name: Test PowerShell
on: push

jobs:
  pester-test:
    name: Pester test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install Dependencies
        shell: pwsh
        run: |
          Install-Module -Name EPS -Repository PSGallery -Force
      - name: Perform a Pester tests
        shell: pwsh
        run: |
          ./Invoke-UnitTests.ps1
